package com.example.myapplication.domain

import com.example.myapplication.data.Pokemon

class PokemonProvider() {
    private val pokemonList = listOf<Pokemon> (
        Pokemon(0, "No Pokemon"),
        Pokemon(1, "Bulbasaur"),
        Pokemon(2, "Ivysaur"),
        Pokemon(3, "Venusaur"),
        Pokemon(4, "Charmander"),
        Pokemon(5, "Charmeleon"),
        Pokemon(6, "Charizard"),
        Pokemon(7, "Squirtle"),
        Pokemon(8, "Wartortle"),
        Pokemon(9, "Blastoise"),
        Pokemon(10, "Caterpie"),
        Pokemon(11, "Metapod"),
        Pokemon(12, "Butterfree"),
        Pokemon(13, "Weedle"),
        Pokemon(14, "Kakuna"),
        Pokemon(15, "Beedrill"),
        Pokemon(16, "Pidgey"),
        Pokemon(17, "Pidgeotto"),
        Pokemon(18, "Pidgeot"),
        Pokemon(19, "Rattata"),
        Pokemon(20, "Raticate"),
        Pokemon(21, "Spearow"),
        Pokemon(22, "Fearow"),
        Pokemon(23, "Ekans"),
        Pokemon(24, "Arbok"),
        Pokemon(25, "Pikachu"),
        Pokemon(26, "Raichu"),
        Pokemon(27, "Sandshrew"),
        Pokemon(28, "Sandslash"),
        Pokemon(29, "Nidoran♀"),
        Pokemon(30, "Nidorina"),
        Pokemon(31, "Nidoqueen"),
        Pokemon(32, "Nidoran♂"),
        Pokemon(33, "Nidorino"),
        Pokemon(34, "Nidoking"),
        Pokemon(35, "Clefairy"),
        Pokemon(36, "Clefable"),
        Pokemon(37, "Vulpix"),
        Pokemon(38, "Ninetales"),
        Pokemon(39, "Jigglypuff"),
        Pokemon(40, "Wigglytuff"),
        Pokemon(41, "Zubat"),
        Pokemon(42, "Golbat"),
        Pokemon(43, "Oddish"),
        Pokemon(44, "Gloom"),
        Pokemon(45, "Vileplume"),
        Pokemon(46, "Paras"),
        Pokemon(47, "Parasect"),
        Pokemon(48, "Venonat"),
        Pokemon(49, "Venomoth"),
        Pokemon(50, "Diglett"),
        Pokemon(51, "Dugtrio"),
        Pokemon(52, "Meowth"),
        Pokemon(53, "Persian"),
        Pokemon(54, "Psyduck"),
        Pokemon(55, "Golduck"),
        Pokemon(56, "Mankey"),
        Pokemon(57, "Primeape"),
        Pokemon(58, "Growlithe"),
        Pokemon(59, "Arcanine"),
        Pokemon(60, "Poliwag"),
        Pokemon(61, "Poliwhirl"),
        Pokemon(62, "Poliwrath"),
        Pokemon(63, "Abra"),
        Pokemon(64, "Kadabra"),
        Pokemon(65, "Alakazam"),
        Pokemon(66, "Machop"),
        Pokemon(67, "Machoke"),
        Pokemon(68, "Machamp"),
        Pokemon(69, "Bellsprout"),
        Pokemon(70, "Weepinbell"),
        Pokemon(71, "Victreebel"),
        Pokemon(72, "Tentacool"),
        Pokemon(73, "Tentacruel"),
        Pokemon(74, "Geodude"),
        Pokemon(75, "Graveler"),
        Pokemon(76, "Golem"),
        Pokemon(77, "Ponyta"),
        Pokemon(78, "Rapidash"),
        Pokemon(79, "Slowpoke"),
        Pokemon(80, "Slowbro"),
        Pokemon(81, "Magnemite")
        )

    fun getPokemonList(): List<Pokemon> {
        return pokemonList
    }

    fun getPokemon(id: Int): Pokemon {
        return pokemonList.find { it.id == id } ?: throw Exception("Pokemon not found")
    }

}